-- Extra profile/detail fields so a Team Leader can maintain full member records.
DO $$
BEGIN
  ALTER TABLE users ADD COLUMN IF NOT EXISTS phone VARCHAR(20);
  ALTER TABLE users ADD COLUMN IF NOT EXISTS college VARCHAR(255);
  ALTER TABLE users ADD COLUMN IF NOT EXISTS course VARCHAR(255);
  ALTER TABLE users ADD COLUMN IF NOT EXISTS year_of_study VARCHAR(50);
  ALTER TABLE users ADD COLUMN IF NOT EXISTS position VARCHAR(255);
  ALTER TABLE users ADD COLUMN IF NOT EXISTS joining_date DATE;
  ALTER TABLE users ADD COLUMN IF NOT EXISTS internship_status VARCHAR(50) DEFAULT 'ACTIVE';
  ALTER TABLE users ADD COLUMN IF NOT EXISTS location VARCHAR(255);
  ALTER TABLE users ADD COLUMN IF NOT EXISTS notes TEXT;
END$$;
