export const APP_CONSTANTS = {
  API_TIMEOUT: 30000,
  MAX_MESSAGE_LENGTH: 2000,
  MAX_FILE_SIZE_MB: 25,
  SIGNED_URL_TTL: 3600,
  TOAST_DURATION: 4000,
  OTP_RESEND_COOLDOWN: 30,
  CLIPBOARD_FEEDBACK_MS: 2000,
  CSRF_COOKIE: 'sn_csrf',
  CSRF_HEADER: 'X-CSRF-Token',
  AUTH_STORAGE_KEY: 'skillnova.auth',
  THEME_STORAGE_KEY: 'theme',
  LOGO_PATH: '/logo.png',
  DEFAULT_PRIORITY: 'MEDIUM',
  QA_CATEGORIES: ['All', 'Projects', 'Reports', 'Meetings', 'Knowledge Base', 'Internship'],
  SOCKET_RECONNECT_DELAY: 1000,
  SOCKET_RECONNECT_DELAY_MAX: 10000,
  TOAST_POSITION: 'top-right',
  TOAST_STYLE: {
    background: 'var(--card)',
    color: 'var(--text)',
    border: '1px solid var(--border)',
    borderRadius: '12px',
    fontSize: '14px',
    padding: '10px 14px',
    boxShadow: '0 8px 24px rgba(0,0,0,0.12)',
  },
};
